server:
  servlet:
    context-path: /api/v1
  port: 8080
logging:
  file:
    name: cs-notification.log
com:
  shaheen:
    fireBase:
      appName: delivery-app
      encodedGoogleCredentials: ${DELIVERY_APP_GOOGLECREDENTIALS}
